sudo: required
services:
- docker
language: java
jdk: openjdk8
script:
- "./gradlew clean build -PbuildNumber=$TRAVIS_BUILD_NUMBER --scan"
- docker build --no-cache --pull -t wisvch/payments:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push wisvch/payments:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  slack:
    rooms:
      secure: yHfjJndPGD1sEnHExos2TXeSs2oSlmJQi6uOkZC3agxk08eGslHoyzzhq0Kw1J3Z+mUI/lmD8K+u4r44Z5zTZ3gudtsV0gKhHGAp8mcKT26GHQ/GO40AULdvo/a3I5eHzM19cRUjwsR4xhI8zjla6yuuD8WHknm7CdpH5s8Kybj3jmswSusOVTZbAwSf5gY1qjZ7Skabuq8b7q/r3nkTh0URu1KivrVNDGz3Vg/31tkJ55BrXK+8kdlyR7564kXwjleG04eQ5o/KqF6L+LShsjwAOVw9kY6rB22kKVr1S3XM7pUk1bU7pjYWa6gH/iw7Hpf+3nJ6byzCdwoedvJQZNXnOnsZFWDFZnDRfEpAORRkPQiBArUbC5GXgiiPsu8eo5wevuFOqs5oQol/bShNYd2qDtG5WQ0UkLbHnK6TtEI3wYrYKuU0oqKxqEpxFqHM7zqSHezsPNXVYsc851XoWu7PNrh9FGaq+t3XeIjE7ZgQL7at4kmIHMZMO9nMlgIUg08S1rCYZ99VcYRr2zEnbbtDaLUDp6G7r9jeuHOcflPnkEjbdVEibPO7C25zggFTZF1eOsg7lncEEXPxHVJShpIlV/C6HOghOZFZ4fu6sv3yOb49cgB2yg/MSawWkH1Ne1dg6S0C5EriPlDFIx+oSr93E7qICEX9oVKTw3LQcyo=
