spring:
  flyway.enabled: false
  ## DATABASE PROPERTIES
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:payments
    username: sa
    password:
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.default_schema: PUBLIC
    show-sql: false

  mail:
    host: localhost
    port: 1025

  security:
    oauth2:
      client:
        registration:
          wisvchconnect:
            client-id: test
            client-secret: test

server:
  servlet:
    context-path: /payments

events:
  username: CH Events
  password: secret
