spring:
  flyway.enabled: false
  ## DATABASE PROPERTIES
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:payments
    username: sa
    password:
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.default_schema: PUBLIC
    show-sql: false

  mail:
    host: localhost
    port: 1025

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  servlet:
    context-path: /

connect:
  issuerUri: https://connect.ch.tudelft.nl/
  clientUri: http://localhost:9000/
  adminGroups: chbeheer,bestuur,hoothub

payments:
  mail.sender: sender@mail.com
  #This is the URL Mollie calls when an order gets an update.
  # https://www.mollie.com/nl/docs/webhook
  webhookUrl: http://localhost:9000/

  # The return Url is the URL to which the user is redirected after the payment.
  # Can (and should) be overriden when creating a new order. This acts as a default fallback.
  returnUrl: http://localhost:9000/

  admin:
    username: admin
    password: password

events:
  username: CH Events
  password: secret
