connect:
  issuerUri: https://connect.ch.tudelft.nl/
  clientUri: http://localhost:9000/

payments:
  #This is the URL Mollie calls when an order gets an update.
  # https://www.mollie.com/nl/docs/webhook
  webhookUrl: http://localhost:9000/

  # The return Url is the URL to which the user is redirected after the payment.
  # Can (and should) be overriden when creating a new order. This acts as a default fallback.
  returnUrl: http://localhost:9000/
